### PR TITLE
Fix Gate bug

### PR DESCRIPTION
**Pull request by 1312255201**
Fix that GateA and GateB doors do not have CD switches

### CODE REVIEW

**Comment by 1312255201** [comment]
https://user-images.githubusercontent.com/50142521/233788807-59efc74f-7c10-49fe-b26b-eccc080991ba.mp4

**Comment by SrLicht** [comment]
I hate mobile Github I accepted the PR by mistake 💀

**Comment by SrLicht** [comment]
You could test if it works correctly if you put at the beginning

```cs
if (door.ActiveLocks > 0 || door._existenceCooldown is not 0) return false;
```
I think that the GetExactState part is not necessary if you know that the door is on cooldown and i don't have a server where to test it at the moment.

**Comment by SrLicht** [comment]
@1312255201 ping pong

**Comment by 1312255201** [comment]
I just woke up in the morning and saw it in the classroom. I don't have a computer now and I have to wait until noon to try it out.a wa

**Comment by 1312255201** [comment]
I found out that this only happens on servers with both nwapis and ex installed.
Then this code cannot solve this problem.
if (door.ActiveLocks > 0 || door._existenceCooldown is not 0) return false;
But the reason for this is the mixed use of plugin frameworks, and if you don't install ex, there won't be any problems

**Comment by 1312255201** [comment]
I found out that this only happens on servers with both nwapis and ex installed.
Then this code cannot solve this problem.
if (door.ActiveLocks > 0 || door._existenceCooldown is not 0) return false;
But the reason for this is the mixed use of plugin frameworks, and if you don't install ex, there won't be any problems

**Pull request merged**
